language: generic 
sudo: required
services: 
  - docker
before_install:
  - docker build -t enginbulut/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true enginbulut/react-test npm test
after_success:
  - docker build -t enginbulut/multi-client ./client
  - docker build -t enginbulut/multi-nginx ./nginx
  - docker build -t enginbulut/multi-server ./server
  - docker build -t enginbulut/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push enginbulut/multi-client
  - docker push enginbulut/multi-nginx
  - docker push enginbulut/multi-server
  - docker push enginbulut/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-541424051176
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY